name: atb_hackathon
description: Open Banking App for ATB Hackathon
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view: ^0.1.6
  after_layout: ^1.0.7+2
  qr_flutter: ^3.2.0
  qrscan: ^0.2.17
  slide_to_confirm: ^0.0.6
  rflutter_alert: ^1.0.3
  beauty_textfield: ^0.0.1
  charts_flutter: ^0.8.1
  flutter_swiper: ^1.1.6
  cupertino_icons: ^0.1.3
  google_nav_bar: ^1.0.4
  line_icons: ^0.2.0
  syncfusion_flutter_core: ^17.4.46
  syncfusion_flutter_charts: ^17.4.46
  flutter_slidable: ^0.5.4
  uuid: ^2.0.4
  introduction_screen: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/items/
    - lib/src/assets/imgs/